---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "5"
  name: keycloak-db-secret
  namespace: keycloak-prod
type: Opaque
stringData:
  username: postgres
  password: pgsqlpassword
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "5"
  name: keycloak-tls
  namespace: keycloak-prod
type: Opaque
stringData:
  tls.crt: |-
    "-----BEGIN CERTIFICATE-----
    MIIDczCCAlugAwIBAgIUecg6til+Ew9HvDvC1gCqlXJduZswDQYJKoZIhvcNAQEL
    BQAwSTEhMB8GA1UEAwwYZGV2ZWxvcG1lbnQua2V5Y2xvYWsub3JnMRcwFQYDVQQK
    DA5UZXN0IEtleWNsb2FrLjELMAkGA1UEBhMCVVMwHhcNMjQwNDEwMTU0MDMyWhcN
    MjUwNDEwMTU0MDMyWjBJMSEwHwYDVQQDDBhkZXZlbG9wbWVudC5rZXljbG9hay5v
    cmcxFzAVBgNVBAoMDlRlc3QgS2V5Y2xvYWsuMQswCQYDVQQGEwJVUzCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKqbxgFSc84s2yu1QF9RGsFQechxe+ss
    wcD0fE49fKTPAh9u7TMU+Z4z5cGPhdftfSYZI8z96K9xXUVwb7s4L8/4NxJ6lJUF
    2Nq+UBfLbnbQTrIrS18zdrc3eTESCrrONz6q153o9tyxlDas4fg9JF+iSDHP+Hhp
    /OLaEwRXQEZ/2ouCxOghW157loT/3Y9DpX82Tpcgg+cdEa44TKd2Ej8ob7Oj+EfP
    Pb9uCeOSwTJh520CA7CtVWbA17eXfaYpJCPl1NenHWXd9rhPItS4yC4oXt9ZxRLa
    0K2aKjnKlUehCHkO5pr0ngWF7nIhMEZVdWsHfpbE9RKzcjHXQrbUh+ECAwEAAaNT
    MFEwHQYDVR0OBBYEFMKRq3W0xwWyK2pCyVAPuJlgYtNmMB8GA1UdIwQYMBaAFMKR
    q3W0xwWyK2pCyVAPuJlgYtNmMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
    BQADggEBAAPxwuG8AVwfDPfOeztKKLSUQLM9WZSFkXGqlSqiQxZWzsN8q1AmT+7P
    jHc/kgLKVjAVbN2jr7TKibVpbGPn/cyEy4pDItCf82NH/aqAfPUUnBbOm1ytyQPW
    s09vqYQ+t+ARjPIDLffin7OYD5EXpscpCBSFkKcNErYt3XoBaHDjYf5o4yI9wsGW
    7jCjG2lYebHnB4hXAYlde2GC9LdQ2EwXVzSgBxaS+eaNwHYz7WS566nURCOPYOk7
    Sjq+jLZ9zXsL4PnIQwE6lv1OVi9+ZTaIwr7O30MD/NovTjaXHcJE+gledZC7qoka
    iAC81/s8QmX+d7kEq9klueqbrlztXQ0=
    -----END CERTIFICATE-----"
  tls.key: |-
    "-----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqm8YBUnPOLNsr
    tUBfURrBUHnIcXvrLMHA9HxOPXykzwIfbu0zFPmeM+XBj4XX7X0mGSPM/eivcV1F
    cG+7OC/P+DcSepSVBdjavlAXy2520E6yK0tfM3a3N3kxEgq6zjc+qted6PbcsZQ2
    rOH4PSRfokgxz/h4afzi2hMEV0BGf9qLgsToIVtee5aE/92PQ6V/Nk6XIIPnHRGu
    OEyndhI/KG+zo/hHzz2/bgnjksEyYedtAgOwrVVmwNe3l32mKSQj5dTXpx1l3fa4
    TyLUuMguKF7fWcUS2tCtmio5ypVHoQh5Duaa9J4Fhe5yITBGVXVrB36WxPUSs3Ix
    10K21IfhAgMBAAECggEABF/vMVx8ZLaIvjOtHWSWg4t9O/MRAuRIaZq7T0RLXGyE
    eOrewTcR+YkKJK759yH7Wg09+kUugMUu55ds/geATlxmiR5EjheyylUj96A7Smeo
    BPCQQ7YtnqAZBvWX+ddM2loGImH1Zo5VJxvCxZtHwf4GzOQw0mGhXu3JnAxitQwK
    g1f0T5kqAqOI21XFhBVf1Fv+q/CInzrZf40HVyXnOqrGNVWMfVHGWMDrEQw7bbS4
    GxHzDYodVroejxRqReSlG7lAIodjIhIzNxr3ruHIbvdSNYzlqVL5KV5n7VKZVfea
    FuURA1vD173RvXhKHVungPzOYuS9gisfTSl2CypzWQKBgQDa7xE5r97abHzc/bkz
    vLRPigshU7iNKK9RkWVagf0bwMpER0RfU5zT4G3vUthHhNcfUAlBw1nE723RfKZJ
    Oz2zPjMn+Wo+ZdwSw9zQC4Jg2tthaTji21pnh79HJHSGxRgIQix773hG0qZ1rbf9
    ykLGXAaR6OUiOWSK5DRCei3ArQKBgQDHfjW6gw90aFpa8qcw0F4lBblNHId86VDF
    nKEmEN694+Yl7DhSXc0pRsbaXG6KI7tnywG6Ad3AUtinwHfkUX381mjj5RbqM/qv
    4r9v+y8LH9lDtS3gR2Zwj2nPF7GClF4vl12ElA9QV7amCwOTk33fes9bxxEK/5nH
    9Hr7RETmhQKBgQC6gM/Gubh5j9OqmoXrugRMgcdLg7uCnLcFIHwb5wJMYyarlZ58
    Kok9wUFFj+hovJRZu1+3YwgVCPYfcDVjyxCbohAILKPCNhmM7scrf7J4edhLGkz4
    jG5uJajfnQGbUUlQt7aXeX+XrZlaRDup+mR6ACkkoSaYyhWJcC/ItbZGHQKBgQCz
    l2xZHxmvqy4EiER5TmwimjeKMu/KROTBMdNlSHStsFgFtdWyWN2UljH4bJPa6nYQ
    55IDWSC/vhVrV3rXYYGxN3iwCRIK/4ZkBxZegluEgUR/jsDhEoYnOQSBOgxEyLrN
    z0+SRhRPONemPW4X0gTURmQcdGZkZ1ySxQZd48S/XQKBgHykwMU3SwztY4bICztP
    SUoBGw3opBxafuhWeeTqivl+D4IG9USuhmeM8AKXoaPXnz0cLZeVONRjgw+LAFjD
    YTT/4zL/cfPwlY8Z2qutX2igCvmbI2K2CkTVTR/FqJAJgEAK1sSSfhgpqVaj3ccS
    mwlT0lXTQltEif3cDkEfo7f9
    -----END PRIVATE KEY-----"