---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "8"
  name: openldap-prod
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "9"
  name: openldap-prod
  namespace: openldap-prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "10"
  name: anyrole
  namespace: openldap-prod
subjects:
  - kind: ServiceAccount
    name: openldap-prod
    namespace: openldap-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "11"
  namespace: openldap-prod
  name: openldap-prod
spec:
  serviceAccount: openldap
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      serviceAccount: openldap
      containers:
        - name: container
          image: rroemhild/test-openldap
          ports:
            - containerPort: 8080
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "12"
  name: openldap-prod
  namespace: openldap-prod
spec:
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 10389
      targetPort: 10389