---
apiVersion: v1 
kind: Secret 
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-db-secret 
  namespace: rhsso-prod
stringData: 
  POSTGRES_DATABASE: "pgsql-rhsso-prod"
  POSTGRES_USERNAME: "pgsql-admin"
  POSTGRES_PASSWORD: "pgsql-password"
  POSTGRES_EXTERNAL_ADDRESS: "keycloak-postgresql.rhsso-prod.svc.cluster.local"
  POSTGRES_EXTERNAL_PORT: "5432"
# of course we have to change the values to real ones
